import React from 'react';

export default function TermsOfService() {
  return (
    <div className="legal-page">
      <div className="legal-content fade-in">
        <a href="/" className="back-link">← Back to Home</a>
        <h1>Terms of Service</h1>
        <p>Last updated: {new Date().toLocaleDateString()}</p>
        
        <section>
          <h2>1. Agreement to Terms</h2>
          <p>By accessing or using Draftly, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>Draftly is an AI-powered email assistant that integrates with your Gmail account to read incoming emails and generate draft responses. Draftly does not send emails automatically without your explicit approval.</p>
        </section>

        <section>
          <h2>3. User Responsibilities</h2>
          <p>You are solely responsible for all content sent from your email account, including AI-generated drafts that you approve. You agree to review all drafts generated by Draftly before sending them to ensure accuracy, tone, and appropriateness.</p>
        </section>

        <section>
          <h2>4. Google API Usage</h2>
          <p>By connecting your Google account, you grant Draftly permission to access your emails in accordance with our Privacy Policy. You may revoke this access at any time through your Google Account Security settings.</p>
        </section>

        <section>
          <h2>5. Disclaimer of Warranties</h2>
          <p>Draftly relies on third-party Artificial Intelligence models. The service is provided "AS IS" without any warranties of any kind. We do not guarantee that the generated drafts will be error-free, factual, or appropriate for all contexts.</p>
        </section>

        <section>
          <h2>6. Limitation of Liability</h2>
          <p>In no event shall Draftly or its developers be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, or goodwill, resulting from your use of the service or reliance on AI-generated content.</p>
        </section>
      </div>
    </div>
  );
}
